spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: board
  redis:
    host: localhost
    port: 6379

eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
